### ISSUE TITLE
dovecot: Fatal: epoll_create()

### ISSUE THREAD

**Issue by dewi-ny-je** [niksula/omnios-build-scripts#2]
I'm getting these on OmniOS r151020 and dovecot 2.2.26.0:

`Nov 12 22:47:52 myServer dovecot: [ID 583609 mail.crit] anvil: Fatal: epoll_create(): No such file or directory`
From https://openindiana.org/pipermail/openindiana-discuss/2016-August/019278.html it looks like it's a matter of setting `--with-ioloop=poll` at compile time.
I'm not sure where to find that option in your build script so I'm not proposing a patch myself.

Thanks

**Comment by lotheac** [comment]
Thanks, workarounds applied and fresh package published.
